{
 "title": "Containers",
 "tags": [
  "thanos",
  "SRE"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{container_label_io_kubernetes_pod_namespace =~\".+\", container_label_io_kubernetes_container_name !=\"POD\"},container_label_io_kubernetes_pod_namespace)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{container_label_io_kubernetes_pod_namespace =~\"$namespace\", container_label_io_kubernetes_container_name!=\"POD\"},container_label_io_kubernetes_container_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_label_io_kubernetes_container_name=\"$container\", container_label_io_kubernetes_pod_namespace=\"$namespace\"}) by (id, container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{ container_label_io_kubernetes_pod_name }}"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{container_label_io_kubernetes_container_name=\"$container\", container_label_io_kubernetes_pod_namespace=\"$namespace\"}) by (container_label_io_kubernetes_pod_namespace,container_label_io_kubernetes_container_name) / count(container_memory_working_set_bytes{container_label_io_kubernetes_container_name=\"$container\", container_label_io_kubernetes_pod_namespace=\"$namespace\"}) by (container_label_io_kubernetes_container_name,container_label_io_kubernetes_pod_namespace)",
     "legendFormat": "limit"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Cpu Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_label_io_kubernetes_container_name=\"$container\", container_label_io_kubernetes_pod_namespace=\"$namespace\"}[60s])) by (id,container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{ container_label_io_kubernetes_pod_name }}"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container_label_io_kubernetes_container_name=\"$container\", container_label_io_kubernetes_pod_namespace=\"$namespace\"} / container_spec_cpu_period{container_label_io_kubernetes_container_name=\"$container\", container_label_io_kubernetes_pod_namespace=\"$namespace\"}) by (container_label_io_kubernetes_pod_namespace,container_name) / count(container_memory_working_set_bytes{container_label_io_kubernetes_container_name=\"$container\", container_label_io_kubernetes_pod_namespace=\"$namespace\"}) by (container_label_io_kubernetes_pod_namespace,container_name) ",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(container_spec_cpu_shares{container_label_io_kubernetes_container_name=\"$container\", container_label_io_kubernetes_pod_namespace=\"$namespace\", prometheus=\"$cluster\"} / 1024) by (container_label_io_kubernetes_pod_namespace,container_label_io_kubernetes_container_name) / count(container_spec_cpu_shares{container_label_io_kubernetes_container_name=\"$container\", container_label_io_kubernetes_pod_namespace=\"$namespace\", prometheus=\"$cluster\"}) by (container_label_io_kubernetes_pod_namespace,container_label_io_kubernetes_container_name) ",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 / kubelet_volume_stats_capacity_bytes * kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}