---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-metrics
  namespace: zookeeper
  labels:
    app: zookeeper
spec:
  type: ClusterIP
  ports:
  - name: tcp-metrics
    port: 9141
    targetPort: metrics
  selector:
    app: zookeeper
