---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zookeeper
  namespace: zookeeper
  labels:
    component: main
spec:
  selector:
    matchLabels:
      app: zookeeper
  endpoints:
  - port: tcp-metrics
    path: /metrics
  namespaceSelector:
    matchNames:
    - zookeeper
