---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    component: main
spec:
  selector:
    matchLabels:
      name: cadvisor
  endpoints:
  - port: http
    scrapeTimeout: 30s
