---
# Source: kafka/templates/servicemonitor-jmx-metrics.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-ing-kafka-jmx-metrics
  namespace: "kafka"
  labels:
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-19.1.3
    app.kubernetes.io/instance: my-ing
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
      app.kubernetes.io/instance: my-ing
      app.kubernetes.io/component: metrics
  endpoints:
    - port: http-metrics
      path: "/"
  namespaceSelector:
    matchNames:
      - kafka
