{
 "title": "Volumes",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "kube-state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Persistent Volume Status by Phase",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_persistentvolume_status_phase{phase=\"Bound\"} == 1",
     "legendFormat": "{{phase}} - {{persistentvolume}}"
    }
   ]
  },
  {
   "title": "Persistent Volume Claim Status by Phase",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_status_phase{phase=\"Pending\"} == 1",
     "legendFormat": "{{phase}} - {{persistentvolumeclaim}} "
    },
    {
     "expr": "kube_persistentvolumeclaim_status_phase{phase=\"Lost\"} == 1",
     "legendFormat": "{{phase}} - {{persistentvolumeclaim}}"
    },
    {
     "expr": "kube_persistentvolumeclaim_status_phase{phase=\"Bound\"} == 1",
     "legendFormat": "{{phase}} - {{persistentvolumeclaim}}"
    }
   ]
  },
  { "title": "kubelet (per namespace)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Persistent Volume Usage per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  { "title": "kubelet (all namespace)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Persistent Volume Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Persistent Volume Inodes Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_inodes_used / kubelet_volume_stats_inodes",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}