---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: ebs-csi-controller
  labels:
    app: ebs-csi-controller
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 3301
    targetPort: metrics
    protocol: TCP
  selector:
    app: ebs-csi-controller
