---
# Source: aws-ebs-csi-driver/templates/serviceaccount-csi-node.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-csi-node-sa
  namespace: kube-system
  labels:
    app.kubernetes.io/name: aws-ebs-csi-driver
    app.kubernetes.io/instance: driver
    helm.sh/chart: aws-ebs-csi-driver-2.13.0
    app.kubernetes.io/version: "1.13.0"
    app.kubernetes.io/component: csi-driver
    app.kubernetes.io/managed-by: Helm
