---
# Source: kafka/templates/jmx-metrics-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-ing-kafka-jmx-metrics
  namespace: "kafka"
  labels:
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-19.1.3
    app.kubernetes.io/instance: my-ing
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
  annotations:
    
    prometheus.io/path: /
    prometheus.io/port: '5556'
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http-metrics
      port: 5556
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: my-ing
    app.kubernetes.io/component: kafka
